-- Context Engine Database Schema v1.2.0
-- SQLite schema for rules, chatlogs, and sequences
-- Generated by schema_generator.py from build/modules/build-schema-database.yaml

-- ============================================================================
-- TABLES
-- ============================================================================

-- Rules table: Core knowledge repository
CREATE TABLE rules (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  domain TEXT,
  confidence REAL CHECK(confidence >= 0.0 AND confidence <= 1.0),
  salience REAL CHECK(salience >= 0.0 AND salience <= 1.0),
  tags_state TEXT NOT NULL,
  lifecycle TEXT NOT NULL DEFAULT 'active',
  tags TEXT NOT NULL,  -- JSON array
  chatlog_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  curated_at TEXT,
  curated_by TEXT,
  metadata TEXT,  -- JSON blob
  FOREIGN KEY(chatlog_id) REFERENCES chatlogs(chatlog_id) ON DELETE RESTRICT
);

-- Chatlogs table: Provenance tracking
CREATE TABLE chatlogs (
  chatlog_id TEXT PRIMARY KEY,
  filename TEXT NOT NULL UNIQUE,
  timestamp TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  agent TEXT,
  processed_at TEXT NOT NULL
);

-- Rule sequences: ID generation state
CREATE TABLE rule_sequences (
  type TEXT PRIMARY KEY,
  next_number INTEGER NOT NULL DEFAULT 1
);

-- Rule relationships: Tracks dependencies, supersessions, conflicts
CREATE TABLE rule_relationships (
  from_rule TEXT NOT NULL,
  to_rule TEXT NOT NULL,
  relationship_type TEXT NOT NULL,
  created_at TEXT NOT NULL,
  notes TEXT,
  FOREIGN KEY(from_rule) REFERENCES rules(id) ON DELETE CASCADE,
  FOREIGN KEY(to_rule) REFERENCES rules(id) ON DELETE CASCADE,
  PRIMARY KEY(from_rule, to_rule, relationship_type)
);

-- Schema_metadata table
CREATE TABLE schema_metadata (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);


-- ============================================================================
-- METADATA STRUCTURE: knowledge_type
-- ============================================================================
--
-- The metadata JSON column supports a knowledge_type object for cognitive
-- classification of rules. This structure is populated by knowledge type
-- classification (Spec 29).
--
-- Structure:
-- {
--   "knowledge_type": {
--     "reference": float (0.0-1.0),    -- Facts, APIs, configs to remember
--     "procedure": float (0.0-1.0),    -- Steps, workflows to follow
--     "decision": float (0.0-1.0),     -- Principles, tradeoffs guiding choices
--     "incident": float (0.0-1.0),     -- Past issues, debugging resolutions
--     "pattern": float (0.0-1.0)       -- Design patterns, conventions
--   }
-- }
--
-- Constraints (enforced by application, not database):
-- - All five keys must be present
-- - All values must be floats in range 0.0-1.0
-- - Sum of all five values must be 0.95-1.05 (normalized weights)
--
-- Example:
-- {
--   "knowledge_type": {
--     "reference": 0.85,
--     "procedure": 0.10,
--     "decision": 0.05,
--     "incident": 0.0,
--     "pattern": 0.0
--   }
-- }
--
-- Query examples:
-- -- Get rules with high procedure weight
-- SELECT * FROM rules
-- WHERE json_extract(metadata, '$.knowledge_type.procedure') > 0.6;
--
-- -- Get rules with high decision weight
-- SELECT * FROM rules
-- WHERE json_extract(metadata, '$.knowledge_type.decision') > 0.6;

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Rules table indexes
CREATE INDEX idx_rules_type ON rules(type);
CREATE INDEX idx_rules_domain ON rules(domain);
CREATE INDEX idx_rules_tags_state ON rules(tags_state);
CREATE INDEX idx_rules_lifecycle ON rules(lifecycle);
CREATE INDEX idx_rules_chatlog ON rules(chatlog_id);
CREATE INDEX idx_rules_confidence ON rules(confidence);

-- Chatlogs table indexes
CREATE INDEX idx_chatlogs_timestamp ON chatlogs(timestamp);
CREATE INDEX idx_chatlogs_processed ON chatlogs(processed_at);

-- Rule_relationships table indexes
CREATE INDEX idx_relationships_from ON rule_relationships(from_rule);
CREATE INDEX idx_relationships_to ON rule_relationships(to_rule);
CREATE INDEX idx_relationships_type ON rule_relationships(relationship_type);

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Initialize rule sequences for all types
INSERT INTO rule_sequences (type, next_number) VALUES ('ADR', 1);
INSERT INTO rule_sequences (type, next_number) VALUES ('CON', 1);
INSERT INTO rule_sequences (type, next_number) VALUES ('INV', 1);
INSERT INTO rule_sequences (type, next_number) VALUES ('PAT', 1);

-- Initialize schema metadata for all types
INSERT INTO schema_metadata (key, value, updated_at) VALUES ('schema_version', '1.2.0', datetime('now'));
INSERT INTO schema_metadata (key, value, updated_at) VALUES ('module_version', 'v1.2.0', datetime('now'));

